### ISSUE TITLE
Will be available in AppStore?

### ISSUE THREAD

**Issue by coderdiaz** [pokeweak/pokemon-weakness-ios#3]
Hi! I just wondered if this application will be possible to publish it in the AppStore as a demonstration of its functionality.

Thank you.

**Comment by skyweb07** [comment]
Hi Javier , i'm trying to make it available for the AppStore, but apple is rejecting because of the pokémon images, we are looking for a workaround :( , once is published I'll update the readme with the link to the appstore ;)

**Comment by coderdiaz** [comment]
Oh, the copyrights attack jeje ok guy, thanks for feedback.
